image:
  repository: romanowalex/migration-application
  tag: v6.0

ports:
  internal: 8080

database:
  username: program
  password: test

ingress:
  enabled: true
  name: migration-application
  domain: local

profile: k8s

resources:
  requests:
    cpu: 1
    memory: 2048Mi
  limits:
    cpu: 1
    memory: 2048Mi
