version: "3"
services:
  postgres:
    image: "postgres:15"
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/

  liquibase-container:
    build:
      context: .
      dockerfile: liquibase-container/Dockerfile
    image: ${REPOSITORY_NAME}/liquibase-container:latest
    container_name: liquibase-container
    command: [ "update" ]
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://postgres:5432/migration
      LIQUIBASE_COMMAND_USERNAME: program
      LIQUIBASE_COMMAND_PASSWORD: test
    depends_on:
      postgres:
        condition: service_healthy

  migration-application:
    build: .
    image: ${REPOSITORY_NAME}/migration-application:v6.0
    container_name: migration-application
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      liquibase-container:
        condition: service_completed_successfully

volumes:
  db-data:

networks:
  default:
    name: database-migration
