ports:
  external: 32432

users:
  - name: program
    password: test

databases:
  - name: migration
    user: program

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 200m
    memory: 512Mi
