---
name: Publish
on:
  push:
    tags:
      - "v*.*"
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2

      - uses: actions/setup-java@v4
        with:
          distribution: "corretto"
          java-version: "17"
          cache: "gradle"

      - name: Build
        run: ./gradlew clean assemble

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build images
        timeout-minutes: 5
        run: |
          docker compose build
          docker build \
            --file liquibase-container/Dockerfile . \
            --tag romanowalex/liquibase-container:latest

      - name: Push images
        run: |
          docker compose push
          docker push romanowalex/liquibase-container:latest

      - name: Create release
        uses: softprops/action-gh-release@v2
